import type { Metadata, Viewport } from "next";
import { Bodoni_Moda, Inter } from "next/font/google";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { site } from "@/data/site";
import { SITE_ORIGIN, SITE_URL } from "@/lib/constants";
import "./globals.css";
import "./motion.css";
import "./intro.css";

/**
 * Fonts — 06-typography.md.
 *
 * Both are variable fonts, so each style is a single file and the weight
 * range comes free; that satisfies the "do not load five weights" rule in
 * 22-performance-budget.md while still giving the display face a real italic
 * for pull quotes. next/font self-hosts them, so there is no render-blocking
 * request to Google and no layout shift.
 */
const bodoni = Bodoni_Moda({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-bodoni",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  metadataBase: SITE_ORIGIN,
  title: {
    default: site.seo.title,
    template: `%s | ${site.brand.name}`,
  },
  description: site.seo.description,
  keywords: [...site.seo.keywords],
  applicationName: site.brand.name,
  authors: [{ name: site.brand.name }],
  creator: site.brand.name,
  publisher: site.brand.name,
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: SITE_URL,
    siteName: site.brand.name,
    title: site.seo.title,
    description: site.seo.description,
    // The OG image is generated by src/app/opengraph-image.tsx and picked up
    // automatically — no manual `images` entry needed.
  },
  twitter: {
    card: "summary_large_image",
    title: site.seo.title,
    description: site.seo.description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  category: "news",
};

export const viewport: Viewport = {
  themeColor: "#F5F2EA",
  colorScheme: "light",
  width: "device-width",
  initialScale: 1,
};

/**
 * Structured data — 20-seo-plan.md.
 * Two nodes only: the publishing organisation and the site itself. Person
 * entities are deliberately omitted because the landing page has no profile
 * pages to back them up.
 */
const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${SITE_URL}/#organization`,
      name: site.brand.name,
      url: SITE_URL,
      description: site.seo.description,
      slogan: site.brand.tagline,
      address: {
        "@type": "PostalAddress",
        addressLocality: site.brand.city,
        addressCountry: "IN",
      },
      email: site.contact.editorialEmail,
      sameAs: [site.contact.instagramUrl],
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: site.brand.name,
      description: site.seo.description,
      inLanguage: "en-IN",
      publisher: { "@id": `${SITE_URL}/#organization` },
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en-IN" className={`${bodoni.variable} ${inter.variable}`}>
      <head>
        {/* Scroll reveals are opacity-0 until an observer fires. With
            JavaScript disabled that observer never runs, so the content is
            forced visible here — 21-accessibility.md: essential information
            must never depend on animation. */}
        <noscript>
          <style
            dangerouslySetInnerHTML={{
              __html:
                "[data-reveal]{opacity:1!important;transform:none!important}.rule{transform:scaleX(1)!important}.line-mask>span{transform:none!important;animation:none!important}",
            }}
          />
        </noscript>
      </head>
      <body className="antialiased">
        {/* Keyboard users land here first — 21-accessibility.md */}
        <a
          href="#main"
          // `label` is applied unconditionally: Tailwind variants only compose
          // with utilities, so `focus:label` would never be generated.
          className="label sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:bg-ink focus:px-5 focus:py-3 focus:text-paper"
        >
          Skip to content
        </a>

        <Header />
        <main id="main">{children}</main>
        <Footer />

        <script
          type="application/ld+json"
          // Static, build-time JSON built from local data — no user input.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
      </body>
    </html>
  );
}
